name: Deploy to Vercel

on:
  push:
    branches:
      - main # Change this to your default branch if it's not "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*' # Use the latest LTS release of Node.js

    - name: Install dependencies
      run: npm ci # or `yarn install` if you're using Yarn

    - name: Deploy to Vercel
      run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
      environment:
        name: vercel deployment