name: Run Playwright and Generate a video, screenshots, and LightHouse HTML Report

on:
  push:
    branches: "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --cpus 2 --memory 4G --user root
    env:
      SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
      NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.SANITY_API_DATASET }} 
      SANITY_API_READ_TOKEN: ${{ secrets.SANITY_API_READ_TOKEN }} 
      SANITY_API_WRITE_TOKEN: ${{ secrets.SANITY_API_WRITE_TOKEN }}
      tests_failed: '' 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libgbm-dev         
          npm ci
          npx playwright install chromium
          npm install -g lighthouse chrome-launcher axe-core chromium wait-on
          npx playwright install-deps  
          npm run build --turbo
      - name: Start the application
        run: |
          export DISPLAY=:1
          npm run start 2>&1 > app.log &
          npx wait-on --timeout 30000 http://localhost:3000 ||  echo "tests_failed=true" >> $GITHUB_ENV
      - name: Print tests_failed
        run: echo "tests_failed=$tests_fail
      - name: Run Playwright tests
        env:
          PLAYWRIGHT_CLI_EXIT_ON_FIRST_FAILURE: '1'
        run: npx playwright test --config=playwright.config.js 

      - name: Install jq
        run: sudo apt-get install jq

      - name: Archive Lighthouse report, videos, and screenshots
        if: env.tests_failed == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            lighthouse-report.json
            test-results/
            **/*.mp4
            **/*.png
      - name: Exit with failure if tests failed
        if: env.tests_failed == 'true'
        run: exit 1